/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod */

#ifndef _Included_com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
#define _Included_com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
 * Method:    registerCallbacks
 * Signature: (Lcom/hamarb123/macos_input_fixes/ScrollCallback;Lcom/hamarb123/macos_input_fixes/KeyCallback;J)V
 */
JNIEXPORT void JNICALL Java_com_hamarb123_macos_1input_1fixes_MacOSInputFixesClientMod_registerCallbacks
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
 * Method:    setTrackpadSensitivity
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_hamarb123_macos_1input_1fixes_MacOSInputFixesClientMod_setTrackpadSensitivity
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
 * Method:    setMomentumScrolling
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hamarb123_macos_1input_1fixes_MacOSInputFixesClientMod_setMomentumScrolling
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod
 * Method:    setInterfaceSmoothScroll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_hamarb123_macos_1input_1fixes_MacOSInputFixesClientMod_setInterfaceSmoothScroll
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
