/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hamarb123_macos_input_fixes_MacOSInputFixesMod */

#ifndef _Included_com_hamarb123_macos_input_fixes_MacOSInputFixesMod
#define _Included_com_hamarb123_macos_input_fixes_MacOSInputFixesMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hamarb123_macos_input_fixes_MacOSInputFixesMod
 * Method:    registerCallbacks
 * Signature: (Ljava/util/function/BiConsumer;J)V
 */
JNIEXPORT void JNICALL Java_com_hamarb123_macos_1input_1fixes_MacOSInputFixesMod_registerCallbacks
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
